# Generated by Django 4.2.30 on 2026-07-07 09:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=200)),
                ('competitor_urls', models.JSONField(blank=True, default=list)),
                ('self_product_doc', models.TextField(blank=True)),
                ('cron', models.CharField(default='0 9 * * *', max_length=100)),
                ('feishu_webhook', models.URLField(blank=True)),
                ('refined_rules', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_status', models.CharField(choices=[('CHANGED', 'Changed'), ('NO_CHANGE', 'No Change'), ('ERROR_CRAWL', 'Error Crawl')], default='CHANGED', max_length=20)),
                ('change_summary', models.TextField(blank=True)),
                ('strategic_intent', models.TextField(blank=True)),
                ('action_suggestion', models.TextField(blank=True)),
                ('evidence_diff', models.TextField(blank=True)),
                ('user_feedback', models.SmallIntegerField(blank=True, null=True)),
                ('user_comment', models.TextField(blank=True)),
                ('html_report_path', models.CharField(blank=True, max_length=255)),
                ('md_table_path', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='intelligence.monitorproject')),
            ],
            options={
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_title', models.CharField(max_length=200)),
                ('source_url', models.URLField()),
                ('raw_markdown', models.TextField(blank=True)),
                ('clean_markdown', models.TextField(blank=True)),
                ('fetch_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='intelligence.monitorproject')),
            ],
            options={
                'ordering': ['-fetch_time', '-id'],
            },
        ),
    ]
