# Generated by Django 4.2.30 on 2026-07-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorproject',
            name='competitor_contexts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='monitorproject',
            name='self_product_doc_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
