# Generated by Django 4.2.30 on 2026-07-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_monitorproject_competitor_contexts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorproject',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
