# Generated by Django 4.2.30 on 2026-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_monitorproject_next_run_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasnapshot',
            name='clean_markdown',
        ),
        migrations.RemoveField(
            model_name='datasnapshot',
            name='raw_markdown',
        ),
        migrations.AddField(
            model_name='datasnapshot',
            name='clean_md_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='datasnapshot',
            name='raw_html_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
