# Generated by Django 4.2.30 on 2026-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0004_remove_datasnapshot_clean_markdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencefeed',
            name='push_status',
            field=models.CharField(choices=[('NOT_PUSHED', 'Not Pushed'), ('PUSHED', 'Pushed'), ('PUSH_FAILED', 'Push Failed')], default='NOT_PUSHED', max_length=20),
        ),
    ]
