# Generated by Django 4.2.30 on 2026-07-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_intelligencefeed_push_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencefeed',
            name='diff_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt_name', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('optimization_reason', models.TextField(blank=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_versions', to='intelligence.intelligencefeed')),
            ],
            options={
                'ordering': ['-version', '-id'],
            },
        ),
    ]
