# Generated by Django 5.0.14 on 2026-07-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0007_datasnapshot_append_only_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencefeed',
            name='competitor_overview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
