# Generated by Django 4.2.30 on 2026-07-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0008_intelligencefeed_competitor_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='intelligencefeed',
            name='raw_diff_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
