# Generated by Django 4.2.30 on 2026-07-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0009_add_raw_diff_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasnapshot',
            name='raw_md_path',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
